name: Full Stack Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - ci/*

jobs:
  build:
    name: CI
    runs-on: ubuntu-18.04
    steps:
      - name: Install non-Haskell dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zlib1g-dev libtinfo-dev libsqlite3-dev libz3-dev

      # If you get 404, check https://github.com/Z3Prover/z3/releases for valid combinations of
      # the parameters.
      - name: Setup Z3
        uses: pavpanchekha/setup-z3@0.2.0
        with:
          version: "4.8.10"
          architecture: "x64"
          distribution: "ubuntu-18.04"

      - name: Setup GHC
        uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.8.4"
          enable-stack: true
          stack-version: 'latest'

      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack884-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack884-

      - name: Build
        run: stack build
      - name: Test
        run: stack test
      - name: Benchmark
        run: stack bench
